### ISSUE TITLE
The logo looks weird

### ISSUE THREAD

**Issue by tusqasi** [alacritty/website#1]
Before:
![image](https://user-images.githubusercontent.com/24749908/128114561-76c7cd69-4773-4abd-a406-a135db0ae173.png)
```css
#logo {
  display: flex;
  align-items: center;
  font-size: 1.7em;
}

#logo-img {
  width: 40px;
}
```
After:
![image](https://user-images.githubusercontent.com/24749908/128114650-57a259af-7184-4470-b28e-5f333dd68676.png)
```css

#logo {
  display: flex;
  align-items: center;
  padding-top: 0.14em; 
  font-size: 2.3em;
}

#logo-img {
  padding-bottom: 0.2em;
  width: 40px;
}
```
I don't know if that was on purpose, but it looked weird to me.
