### ISSUE TITLE
Add light theme for website

### ISSUE THREAD

**Issue by spenserblack** [alacritty/website#35]
I know, developers like dark themes because light attracts bugs :laughing:

Depending on the monitor and light level in the room, sometimes a dark theme can be hard-to-read. On my laptop, I frequently switch my system theme depending on where I am. A light theme for your website would be much appreciated!

**Comment by chrisduerr** [comment]
I have no interest in maintaining a light theme myself.

**Comment by spenserblack** [comment]
So that means no interest in receiving a PR, either?

**Comment by chrisduerr** [comment]
I don't have any faith a PR would add it in a way I'd be happy with.

**Comment by spenserblack** [comment]
Fair enough. FWIW my plan was to do something vaguely like this to automatically select the appropriate colors:

```css
:root {
  --color-fg: black;
  --color-bg: white;
  color: var(--color-fg);
  background-color: var(--color-bg);
}
@media (prefers-color-scheme: dark) {
  :root {
    --color-fg: white;
    --color-bg: black;
  }
}
```

For a first iteration I wasn't concerned about an interactive element or saving down the selected/overridden theme. The site as it is is pretty simple (and that's good!) and I wouldn't want to add that much complexity.
